# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-16 00:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Traveller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('number', models.IntegerField()),
                ('travel_start_date', models.DateTimeField()),
                ('travel_end_date', models.DateTimeField()),
                ('country', models.CharField(max_length=20)),
            ],
        ),
    ]
